# ──────────────────────────────────────────────────────────────
# Global settings
# ──────────────────────────────────────────────────────────────

instance: https://sh.itjust.works
community: Asslips

# Logging & debug
log_dir: logs
debug: true

# Optional filters & gating
toxicity_filter: false   # (kept for compatibility; filtering uses toxic_words below)
max_replies: 3
comment_roll: 70
reply_delay_min: 300   # seconds between comments (lower)
reply_delay_max: 600   # seconds between comments (upper)
initial_post: false
max_focus_retries: 5   # default for all bots
#post_stagger_seconds: 600   # Wait this many seconds between ANY bots posting a new thread --- This could cause issues and bots could still post back to back - it's better to set each bot to post at x seconds.

# Fallback configuration
fallback_file: fallbacks_expanded.yaml
fallback_history_size: 10

# NEW: custom toxic words (any occurrence will be filtered out)
toxic_words:
  - homework
  - assignment
  - assault

# Bot definitions
bots:
  - name: 
    model: 
    username: 
    password: 
    postfreq: 3
    max_new_tokens: 128
    min_new_tokens: 32
    max_new_tokens_cap: 256
    strict_mode: true          # enable the dynamic strictness engine
    mention_strict_tries: 5    # how many attempts to enforce “must-mention”
    complete_strict_tries: 5   # how many attempts to enforce “complete thought”
    length_initial: 10         # initial length threshold
    length_min: 0              # minimum length allowed after full relaxation
    fallback_prompt: "My colon just detonated a glacier of {topics} rancid turd ice and the stench is rewriting my DNA." #You can leave fallback_prompt blank or omit it on bots that should continue to use the YAML‐pool.
    ban_pop: false
    ban_unicode_escapes: true
    # max_focus_retries: 5   # GLOBAL ALREADY SET
    post_stagger_seconds: 0

  - name: 
    model: 
    username: 
    password: 
    postfreq: 3
    max_new_tokens: 128
    min_new_tokens: 32
    max_new_tokens_cap: 256
    strict_mode: true          # enable the dynamic strictness engine
    mention_strict_tries: 5    # how many attempts to enforce “must-mention”
    complete_strict_tries: 5   # how many attempts to enforce “complete thought”
    length_initial: 10         # initial length threshold
    length_min: 0              # minimum length allowed after full relaxation
    fallback_prompt: "I’m drowning in a tidal wave of mutant sphincter cheese {topics} oozing from a thousand butt cracks." #You can leave fallback_prompt blank or omit it on bots that should continue to use the YAML‐pool.
    ban_pop: false
    ban_unicode_escapes: false
    # max_focus_retries: 5   # GLOBAL ALREADY SET
    post_stagger_seconds: 600